version: '3.9'
services:

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - 'pg-data:/var/lib/postgresql/data'
      - './pg-init-scripts/init-1.sh:/docker-entrypoint-initdb.d/init-1.sh'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_MULTIPLE_DATABASES: app,app_test
    ports:
      - 5432:5432

  app:
    build: .
    container_name: app
    image: app
    environment:
      PG_URL: 'postgres://user:pass@postgres:5432/app'
      PG_URL_TEST: 'postgres://user:pass@postgres:5432/app_test'
    ports:
      - 80:80
    depends_on:
      - postgres

  integration:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    container_name: integration
    image: integration
    depends_on:
      - app

volumes:
  pg-data:
