app:
  name: 'news-telegram-bot'
  version: '1.0.0'

http:
  port: '80'

logger:
  log_level: 'debug'
  rollbar_env: 'news-telegram-bot'

postgres:
  pool_max: 2

telegram:
  base_url: 'https://api.telegram.org/'

grabber:
  sleep: 3600
