// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/jokius/news-telegram-bot/internal/entity"
)

// MockUser is a mock of User interface.
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *MockUserMockRecorder
}

// MockUserMockRecorder is the mock recorder for MockUser.
type MockUserMockRecorder struct {
	mock *MockUser
}

// NewMockUser creates a new mock instance.
func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &MockUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUser) EXPECT() *MockUserMockRecorder {
	return m.recorder
}

// AuthToken mocks base method.
func (m *MockUser) AuthToken(id, code string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AuthToken", id, code)
}

// AuthToken indicates an expected call of AuthToken.
func (mr *MockUserMockRecorder) AuthToken(id, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthToken", reflect.TypeOf((*MockUser)(nil).AuthToken), id, code)
}

// TelegramCallback mocks base method.
func (m *MockUser) TelegramCallback(arg0 entity.TelegramResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TelegramCallback", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// TelegramCallback indicates an expected call of TelegramCallback.
func (mr *MockUserMockRecorder) TelegramCallback(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TelegramCallback", reflect.TypeOf((*MockUser)(nil).TelegramCallback), arg0)
}

// MockMessenger is a mock of Messenger interface.
type MockMessenger struct {
	ctrl     *gomock.Controller
	recorder *MockMessengerMockRecorder
}

// MockMessengerMockRecorder is the mock recorder for MockMessenger.
type MockMessengerMockRecorder struct {
	mock *MockMessenger
}

// NewMockMessenger creates a new mock instance.
func NewMockMessenger(ctrl *gomock.Controller) *MockMessenger {
	mock := &MockMessenger{ctrl: ctrl}
	mock.recorder = &MockMessengerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessenger) EXPECT() *MockMessengerMockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *MockMessenger) Auth(id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Auth", id)
}

// Auth indicates an expected call of Auth.
func (mr *MockMessengerMockRecorder) Auth(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockMessenger)(nil).Auth), id)
}

// GroupList mocks base method.
func (m *MockMessenger) GroupList(id string, groups []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GroupList", id, groups)
}

// GroupList indicates an expected call of GroupList.
func (mr *MockMessengerMockRecorder) GroupList(id, groups interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GroupList", reflect.TypeOf((*MockMessenger)(nil).GroupList), id, groups)
}

// IncorrectFormat mocks base method.
func (m *MockMessenger) IncorrectFormat(id, command string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncorrectFormat", id, command)
}

// IncorrectFormat indicates an expected call of IncorrectFormat.
func (mr *MockMessengerMockRecorder) IncorrectFormat(id, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncorrectFormat", reflect.TypeOf((*MockMessenger)(nil).IncorrectFormat), id, command)
}

// RemovedGroup mocks base method.
func (m *MockMessenger) RemovedGroup(id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemovedGroup", id)
}

// RemovedGroup indicates an expected call of RemovedGroup.
func (mr *MockMessengerMockRecorder) RemovedGroup(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovedGroup", reflect.TypeOf((*MockMessenger)(nil).RemovedGroup), id)
}

// StartDateUpdated mocks base method.
func (m *MockMessenger) StartDateUpdated(id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartDateUpdated", id)
}

// StartDateUpdated indicates an expected call of StartDateUpdated.
func (mr *MockMessengerMockRecorder) StartDateUpdated(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDateUpdated", reflect.TypeOf((*MockMessenger)(nil).StartDateUpdated), id)
}

// URLAdded mocks base method.
func (m *MockMessenger) URLAdded(id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "URLAdded", id)
}

// URLAdded indicates an expected call of URLAdded.
func (mr *MockMessengerMockRecorder) URLAdded(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URLAdded", reflect.TypeOf((*MockMessenger)(nil).URLAdded), id)
}

// UnknownError mocks base method.
func (m *MockMessenger) UnknownError(id, text string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnknownError", id, text)
}

// UnknownError indicates an expected call of UnknownError.
func (mr *MockMessengerMockRecorder) UnknownError(id, text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnknownError", reflect.TypeOf((*MockMessenger)(nil).UnknownError), id, text)
}

// UnknownSource mocks base method.
func (m *MockMessenger) UnknownSource(id, url string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnknownSource", id, url)
}

// UnknownSource indicates an expected call of UnknownSource.
func (mr *MockMessengerMockRecorder) UnknownSource(id, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnknownSource", reflect.TypeOf((*MockMessenger)(nil).UnknownSource), id, url)
}

// MockSource is a mock of Source interface.
type MockSource struct {
	ctrl     *gomock.Controller
	recorder *MockSourceMockRecorder
}

// MockSourceMockRecorder is the mock recorder for MockSource.
type MockSourceMockRecorder struct {
	mock *MockSource
}

// NewMockSource creates a new mock instance.
func NewMockSource(ctrl *gomock.Controller) *MockSource {
	mock := &MockSource{ctrl: ctrl}
	mock.recorder = &MockSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSource) EXPECT() *MockSourceMockRecorder {
	return m.recorder
}

// AuthURL mocks base method.
func (m *MockSource) AuthURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// AuthURL indicates an expected call of AuthURL.
func (mr *MockSourceMockRecorder) AuthURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthURL", reflect.TypeOf((*MockSource)(nil).AuthURL))
}

// GetGroupsMessages mocks base method.
func (m *MockSource) GetGroupsMessages() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetGroupsMessages")
}

// GetGroupsMessages indicates an expected call of GetGroupsMessages.
func (mr *MockSourceMockRecorder) GetGroupsMessages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupsMessages", reflect.TypeOf((*MockSource)(nil).GetGroupsMessages))
}

// GetToken mocks base method.
func (m *MockSource) GetToken(code string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToken", code)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToken indicates an expected call of GetToken.
func (mr *MockSourceMockRecorder) GetToken(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToken", reflect.TypeOf((*MockSource)(nil).GetToken), code)
}

// Name mocks base method.
func (m *MockSource) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSourceMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSource)(nil).Name))
}

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// AddGroupByURL mocks base method.
func (m *MockUserRepo) AddGroupByURL(id, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGroupByURL", id, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddGroupByURL indicates an expected call of AddGroupByURL.
func (mr *MockUserRepoMockRecorder) AddGroupByURL(id, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGroupByURL", reflect.TypeOf((*MockUserRepo)(nil).AddGroupByURL), id, url)
}

// AddToken mocks base method.
func (m *MockUserRepo) AddToken(id, token, sourceName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToken", id, token, sourceName)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToken indicates an expected call of AddToken.
func (mr *MockUserRepoMockRecorder) AddToken(id, token, sourceName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToken", reflect.TypeOf((*MockUserRepo)(nil).AddToken), id, token, sourceName)
}

// RemoveGroup mocks base method.
func (m *MockUserRepo) RemoveGroup(id, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveGroup", id, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveGroup indicates an expected call of RemoveGroup.
func (mr *MockUserRepoMockRecorder) RemoveGroup(id, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveGroup", reflect.TypeOf((*MockUserRepo)(nil).RemoveGroup), id, url)
}

// UpdateStartDate mocks base method.
func (m *MockUserRepo) UpdateStartDate(id string, date time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStartDate", id, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStartDate indicates an expected call of UpdateStartDate.
func (mr *MockUserRepoMockRecorder) UpdateStartDate(id, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStartDate", reflect.TypeOf((*MockUserRepo)(nil).UpdateStartDate), id, date)
}

// MockUserWebAPI is a mock of UserWebAPI interface.
type MockUserWebAPI struct {
	ctrl     *gomock.Controller
	recorder *MockUserWebAPIMockRecorder
}

// MockUserWebAPIMockRecorder is the mock recorder for MockUserWebAPI.
type MockUserWebAPIMockRecorder struct {
	mock *MockUserWebAPI
}

// NewMockUserWebAPI creates a new mock instance.
func NewMockUserWebAPI(ctrl *gomock.Controller) *MockUserWebAPI {
	mock := &MockUserWebAPI{ctrl: ctrl}
	mock.recorder = &MockUserWebAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserWebAPI) EXPECT() *MockUserWebAPIMockRecorder {
	return m.recorder
}

// VkCallback mocks base method.
func (m *MockUserWebAPI) VkCallback(arg0 *entity.User) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VkCallback", arg0)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VkCallback indicates an expected call of VkCallback.
func (mr *MockUserWebAPIMockRecorder) VkCallback(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VkCallback", reflect.TypeOf((*MockUserWebAPI)(nil).VkCallback), arg0)
}
