name: tests
on: pull_request

jobs:
  vm-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: app
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      # required to compile pg ruby gem
      - name: install PostgreSQL client
        run: sudo apt-get install libpq-dev
      - name: Run migrations
        run: migrate -path migrations -database 'postgres://user:pass@localhost:5432/app?sslmode=disable' up
      - name: Run tests
        env:
          PG_URL_TEST: postgres://user:pass@localhost:5432/app?sslmode=disable
        run: go test ./..